export const expectedResponse = {
    username: "testuser@qa.com",
    permissions: null,
    investorType: "PRIVATE_PERSON",
    registrationStep: "IDENTIFICATION",
    status: "REGISTERED",
    firstName: "Tester",
    accountBalance: 0.0,
    unsettledBalance: 0.0,
    bankAccountNumbers: [],
    number: "52940",
    idDocumentsStatus: "NO_DOCUMENTS",
    displayPortfolio: false,
    inUploadStep: false,
    vip: false,
    vipConfirmed: false,
    notifications: {
      unreadPushNotifications: 0,
    },
    currency: "EUR",
    language: "EN",
    hasChangedCurrency: true,
    registeredAt: "2024-07-29",
    isShowPep: false,
    isPepOrPrivateInvestorNotOwner: true,
    isShowLastAgreementPopup: false,
    isShowKycPopup: false,
    isShowTwoFaPopup: false,
    usingTwoFa: false,
    updatePersonalData: false,
    shouldUpdatePrivateInvestorBirthDate: false,
    isShowPlAssignmentAgreementPopup: false,
    isDeleteRequestAllowed: true,
    isShowProductTypePopup: false,
    id: 42941,
  };